### ISSUE TITLE
Create donators end screen widget + active play time widget

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#10]
End screen should have:
* top donators widget
* who has played the most hours on server
* localrecords for the map
* server ranks

so 4 widgets, no more :)

**Comment by oliverde8** [comment]
Well, 1.1 :smile:

**Comment by reaby** [comment]
i try to have this on 1.0.0 as it was requested few times lately...

**Comment by reaby** [comment]
done, update available at dev.
