### ISSUE TITLE
Memory Leaj

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#129]
I already did a profiling of 1 hour, connecting disconnecting fake players non stop. Result is this plugins leaks : 
* manialivepluginsexpansionmenumenu,371844672
* manialivepluginsexpansionwidgets_personalbestwidgets_personalbest",96644040
* manialivepluginsexpansionwidgets_timeswidgets_times,84791160
* manialivepluginsexpansioncommunicationcommunication,22442208
* manialivepluginsexpansiondedimania_scriptdedimania_script,21431928
* manialivepluginsexpansiondatabasedatabase,8928160
* manialivepluginsexpansiondebugtooldebugtool,5563824
* manialivepluginsexpansioncommunicationguiwidgetsmessager,3682864
* manialivepluginsexpansionlocalrecordslocalrecords,1444608
* manialivepluginsexpansionmapratingsmapratings,861304
* manialivepluginsexpansionwidgets_tm_toppanelwidgets_tm_toppanel,591488
* manialivepluginsexpansionmapsmaps,540952
* manialivepluginsexpansionwidgets_resskipwidgets_resskip",517384
* manialivepluginsexpansionjoinleavemessagejoinleavemessage,359792
* manialivepluginsexpansionwidgets_chatenhancementwidgets_chatenhancement",327312
* manialivepluginsexpansionwidgets_endrankingswidgets_endrankings",233608
* manialivepluginsexpansionwidgets_checkpointprogresswidgets_checkpointprogress",139064
* manialivepluginsexpansioncoreanalytics,80272
* manialivepluginsexpansionloadscreenloadscreen,74184
* manialivepluginsexpansionserverstatisticsserverstatistics,"-1256"

Problem is the profiler catches memory usage for new windows but it doesn't see that the memory is being released as that is done by the Gui Handler. So need to make it better. But already have an idea about where to look for.

**Comment by reaby** [comment]
looks like GUI  windows and widgets had some memory problems... I hope I found a solution at "dev_ui" branch. it contains some fixes, but it needs testing if it really fixed the problem..

**Comment by reaby** [comment]
fixed.
