### ISSUE TITLE
More control over Voting

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#140]

**Comment by reaby** [comment]
I enhanced the votes manager. 

It has now options to:
- added dropdown menus for vote options (so you don't need to remember which number means what)
- limit votes per map (ie. allow only vote skip once)
- limit map restarts (ie. 2 maximum restarts allowed)
- mxVote options and ratios: allow players to add temporarily maps from mx
- and normal voting options
