### ISSUE TITLE
Error in bets plugin

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#161]
#0 /libraries/ManiaLivePlugins/eXpansion/Core/types/ErrorHandler.php(15): ManiaLive\Application\ErrorHandling::createExceptionFromError(8, 'Trying to get p...', '//...', 194)
#1 /libraries/ManiaLivePlugins/eXpansion/Bets/Bets.php(194): ManiaLivePlugins\eXpansion\Core\types\ErrorHandler::createExceptionFromError(8, 'Trying to get p...', '//...', 194, Array)
#2 /libraries/ManiaLivePlugins/eXpansion/Bets/Bets.php(188): ManiaLivePlugins\eXpansion\Bets\Bets->announceTotal('xxxx')
#3 [internal function]: ManiaLivePlugins\eXpansion\Bets\Bets->billSetSuccess(Object(ManiaLivePlugins\eXpansion\Core\types\Bill))
#4 /libraries/ManiaLivePlugins/eXpansion/Core/types/Bill.php(105): call_user_func_array(Array, Array)
#5 /libraries/ManiaLivePlugins/eXpansion/Core/BillManager.php(136): ManiaLivePlugins\eXpansion\Core\types\Bill->validate()
#6 /vendor/maniaplanet/manialive-lib/ManiaLive/DedicatedApi/Callback/Event.php(92): ManiaLivePlugins\eXpansion\Core\BillManager->onBillUpdated(69, 4, 'Payed', 2938496)
#7 /vendor/maniaplanet/manialive-lib/ManiaLive/Event/Dispatcher.php(132): ManiaLive\DedicatedApi\Callback\Event->fireDo(Object(ManiaLivePlugins\eXpansion\Core\BillManager))
#8 /vendor/maniaplanet/manialive-lib/ManiaLive/Application/Application.php(123): ManiaLive\Event\Dispatcher::dispatch(Object(ManiaLive\DedicatedApi\Callback\Event))
#9 /bootstrapper.php(73): ManiaLive\Application\Application->run()
#10 {main}

**Comment by reaby** [comment]
should be fixed
