### ISSUE TITLE
MX Download API send new Headers

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#163]
So, 

>Just a small heads-up, the MX track download API got a small optional change. Whenever downloading a track (GET /tracks/download/{id}), you can now optionally specify a header X-ManiaPlanet-ServerLogin with as value the server's login string. Setting this is somewhat recommended, but again fully optional. If you wish, you can implement this change in your controller.
It's used to help creators find servers who've added their maps, basically advertising that exact server to them.

**Comment by reaby** [comment]
Current implementation has limits, have to see if cUrl or something else could be used as async somehow...

**Comment by reaby** [comment]
As was said at #165 comments, MX API currently redirects to https, which is not implemented for the current system. I guess it must be fixed during this weekend :)
