### ISSUE TITLE
GUI issues with number-only logins

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#166]
Some issues has been found with number only logins. windows / widgets doesn't get removed from hud, even if Window::erase() is called, also redrawing widget/window has problems.
(local records, live and dedimania gets redrawn over and over again as map changes, also current and next map widgets. the gui is a mess after few map changes :+1:)

This seams to affect also redrawing gui elements.
(Changing expansion configuration tabs works only once, after that you can't really change a tab)

Maniascript::stringifyAsList($loginsarray) also fails with normal and numberonly logins as it mixes strings with integers, and ingame maniascript gives parse errors.

**Comment by reaby** [comment]
partial fix available at dev!
manialinks sent to personalized (for single login) still fails to remove from the view, "global" manialinks works.

**Comment by oliverde8** [comment]
Issue completely fixed on dev of manialive-lib, :smile:
