### ISSUE TITLE
Undefined property: ManiaLivePlugins\eXpansion\Gui\Config::$uiTextureBase

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#171]
#0 /libraries/ManiaLivePlugins/eXpansion/Core/types/ErrorHandler.php(15): ManiaLive\Application\ErrorHandling::createExceptionFromError(8, 'Undefined prope...', '/home/gameserve...', 38)
#1 /libraries/ManiaLivePlugins/eXpansion/Gui/Windows/WindowTextures.php(38): ManiaLivePlugins\eXpansion\Core\types\ErrorHandler::createExceptionFromError(8, 'Undefined prope...', '/home/gameserve...', 38, Array)
#2 /libraries/ManiaLivePlugins/eXpansion/Gui/Windows/ConfirmDialog.php(24): ManiaLivePlugins\eXpansion\Gui\Windows\WindowTextures->onConstruct()
#3 /vendor/maniaplanet/manialive-lib/ManiaLive/Gui/Window.php(210): ManiaLivePlugins\eXpansion\Gui\Windows\ConfirmDialog->onConstruct()
#4 /vendor/maniaplanet/manialive-lib/ManiaLive/Gui/Window.php(97): ManiaLive\Gui\Window->__construct('???.', Array)
#5 /libraries/ManiaLivePlugins/eXpansion/Gui/Gui.php(257): ManiaLive\Gui\Window::Create('???.')
#6 [internal function]: ManiaLivePlugins\eXpansion\Gui\Gui::showConfirmDialog('???.', 65)
#7 /vendor/maniaplanet/manialive-lib/ManiaLive/Gui/ActionHandler.php(71): call_user_func_array(Array, Array)
#8 /vendor/maniaplanet/manialive-lib/ManiaLive/DedicatedApi/Callback/Event.php(66): ManiaLive\Gui\ActionHandler->onPlayerManialinkPageAnswer(67, '???.', '66', Array)
#9 /vendor/maniaplanet/manialive-lib/ManiaLive/Event/Dispatcher.php(132): ManiaLive\DedicatedApi\Callback\Event->fireDo(Object(ManiaLive\Gui\ActionHandler))
#10 /vendor/maniaplanet/manialive-lib/ManiaLive/Application/Application.php(123): ManiaLive\Event\Dispatcher::dispatch(Object(ManiaLive\DedicatedApi\Callback\Event))
#11 /bootstrapper.php(73): ManiaLive\Application\Application->run()
#12 {main}

**Comment by oliverde8** [comment]
I leave this to yo reaby, not sure which parameter you wish to use instead :smile:

**Comment by reaby** [comment]
should be fixed, the baseurl is not needed anymore, so all references for it is not needed anymore.
for some reason the netbeans refactor->safe remove wasn't able to find this..
should be fixed for now.
