### ISSUE TITLE
Warmup can't be ended in scripted gamemodes

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#188]
it should work mainly with 
/adm ER
also preferably with
/adm res

preferably it doesn't work with scripted laps :(

**Comment by reaby** [comment]
laps gamemode script doesn't have trigger to end warmup..
can't fix, gamemode itself needs a modification. Closing ticket.

**Comment by oliverde8** [comment]
just putting link to the forum post : https://forum.maniaplanet.com/viewtopic.php?f=470&t=37481
