### ISSUE TITLE
ranks calculation enhancements

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#192]
* update ranks after maplist has been modified
* make possible of manually reset ranks for tournaments
* make config variables to lower min rec count for having ranking

**Comment by oliverde8** [comment]
1/ Is already the case normally, The way it works is the rankings are constantly updated in the database after each map. Then when rankings are displayed it uses that DB with list of maps on the server. 
The only case this doesen't work is for DB imported from other tools such. 

2/ Already possible it will just completely freeze eXpansion, so put it in a job. 
I am not sure why it is needed? Again normally it is only needed when importing a DB from another tool. If not eXpansion will maintain the list up to date.

3/ Ok
