### ISSUE TITLE
remove "minimap" plugin

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#194]
It causes all players to disconnect when map changes, 
IF gamemode has no support for minimap.

This plugin will only but cause trouble (it has already done it)

**Comment by oliverde8** [comment]
we should maybe have a package of expermintal plugins to put this kind of things that crashes the game XD

Maybe, maybe one day Nadeo will fix the minimap crash :smile:

**Comment by reaby** [comment]
plugin removed.
