### ISSUE TITLE
join/leave message -> add option to show only admins

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#195]
yes, add config option to show messages only admins

**Comment by oliverde8** [comment]
Hmm I think : 
We should do a Guest group which is basically permissions for all players not in any group. 

Then add simply a permission, show_join message

if player that joins has the permission then gogo. By default everyone has the permission. 

This would make this kind of feature much easier to put in place ?

**Comment by reaby** [comment]
hmm.. it might make the settings too diverse you think?
i think, you firstly look for certaint feature from plugin settings, not perhaps from permissions ?
but :+1: for guest group, it might be needed later on
