### ISSUE TITLE
Improve permissions

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#211]
Add a default Guest group for all players in the server that isn't admin. And add posibility to add permissions to it

**Comment by reaby** [comment]
This feature is requested multiple times now and is blocking other plugin development. 
Changing priority up

**Comment by oliverde8** [comment]
Just added the Guest feature, so all users that is not in any other group is in that group automatically.

Permissions of the group ca be changed. You can allow guest to even stop the server. By default no permissions is set. 

As with Master Admin Group, the title of the group can't be changed in the interface but can be in the config file. 

*There seem to be a bug with the menu not handling well this case* So I keep it open for now
