### ISSUE TITLE
Display leave message while 'only show for admins' is on

### ISSUE THREAD

**Issue by tomvlk** [eXpansionPluginPack/eXpansion#219]
Hey,
When turning the feature on to only show the connect/disconnect messages to admins and leave the leave messages on on, it will show it for all players.
But when you disable the leave message it won't show for the admins but hide for all players.

I guess something is not right there.

**Comment by oliverde8** [comment]
Confirming, 

The join message works as expected, but the leave message shows to all players. It should show only to admins.

Need to reworks this, so that the permissions can be set up by user group.  The option will in that case disappear.
