### ISSUE TITLE
Plugin List window error due to size

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#227]
The plugin list window works fine with current version of eXpansion. But if you add a few custom plugins to eXpansion it won't work. 

The issue is the xml is to big and is being rejected. 

So we need to remove the nice scroller & replace it with and old style pagination

**Comment by reaby** [comment]
Way to reduce the windows size, would be to remove all descriptions from the buttons.
I removed some already.

**Comment by oliverde8** [comment]
you mean the tooltips? But those are practical information XD

Old style pager XD

**Comment by oliverde8** [comment]
Switched to old style pager.
