### ISSUE TITLE
Additions to adding maps from MX 

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#242]
Mapname should be configurable
(now it's %author%_%mapname%_%mxid%.map.gbx)

give possibility to change it

**Comment by oliverde8** [comment]
Map name can now be configured using some patterns : {map_author}, {map_name}, {map_environment}, {map_vehicle}, {map_type}, {map_style}, {mx_id}, {server_title}

The default pattern is `{server_title}/{map_author}_{map_name}_{mx_id}.map.gbx`

Directories are generated automatically.
