### ISSUE TITLE
improve ingame help

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#272]
Create a new plugin to handle help related stuff.

- [x] see if we can do scrollable canvas using frame clip
- [x] make parser to generate manialink from markdown
- [x] see if we can import wiki contents to ingame
- [x] see a way to include current help
- [x] generate admin short commands help
- [x] generate chat commands help

**Comment by oliverde8** [comment]
I think we can close this?

I added another issue for chat help improvements. #276
