### ISSUE TITLE
Dedimania: with 1 or less checkpoints on map will show new times, even will not save them

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#59]

**Comment by chillinski** [comment]
Just want to point out that a map in trackmania is not allowed to have zero checkpoints.
Beside this, great work so far.

**Comment by MiniGod** [comment]
@chillinski A multi-lap map must have 1 or more checkpoints. A point to point map does not need any checkpoints.

**Comment by chillinski** [comment]
Thanks for this advice.

**Comment by reaby** [comment]
i think this is fixed long ago.
