### ISSUE TITLE
log more info for log files

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#72]
Currently we log maybe too less. See if we can write more logs :)

**Comment by oliverde8** [comment]
maybe clean up some logs as well :smile:

**Comment by oliverde8** [comment]
We did quite ome progress, mobing to next release to make it even better

**Comment by oliverde8** [comment]
I normalized log output. 

To log in a plugin simply need to do : 
```
$this->console('Message to log & display in console'); 
```
This will prefix the message properly with the plugin vendor & name.

If you need to log any other place just use the static methods in the Helper class. 
```
Helper::log('Message to log & display in console', array('eXpansion', 'testPlugin')); 
```
This will print
> [eXpansion][testPlugin] Message to log & display in console
And log
> [DATE] [eXpansion][testPlugin] Message to log & display in console

To debug anything use 
```
Helper::debug(); 
```
This will print & log the message only if debug is enabled in the configurations.

I fixed multiple logs to normalize them around the code.

**Comment by oliverde8** [comment]
Need to remove some debug's in the code to actually close it, they do manually print_r or echo's
